# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
tasks:
  - init: yarn
    command: yarn start

ports:
  - port: 3000
    onOpen: open-preview
    description: Website preview
